# Generated by Django 5.0.3 on 2024-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_reivews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Reivew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('img', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Reivew',
        ),
        migrations.DeleteModel(
            name='Reivews',
        ),
    ]
