# Generated by Django 4.2.5 on 2024-04-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('20percentoff', 20), ('30percentoff', 30), ('10percentoff', 10), ('freedelivery', 100)], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
            ],
        ),
    ]
